name: "publish"

on:
  push:
    branches:
      - main
    paths:
      - package/**

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org

      - name: Publish package
        run: npm publish --access public
        working-directory: package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
